### ISSUE TITLE
App crashes when opened

### ISSUE THREAD

**Issue by akulkarni9** [malikov/Authenticate.me-client-cordova-ionic#4]
Hi,

I cloned your repository into my system and built it as instructed. Then I got apk file and when I installed it in my Android phone, it didn't open.  It displayed a message "Unfortunately Authentication.me has stopped". I tried 3 times and I got same message. Maybe you should try it in Android 4.2 ( Jelly Bean )

**Comment by TolotraRam** [comment]
Hi,
Just remove and add again all pulgins !!!
Cheers

**Comment by akulkarni9** [comment]
Great, it worked... So you meant to tell that plug ins were outdated?

**Comment by TolotraRam** [comment]
No, i don't think so, i think they are installed since you clone the repo but not with all files they need, it's just a suggestion.

**Comment by malikov** [comment]
Hey @akulkarni9 , 

@TolotraRam is right it happens often some files are probably missing for some plugins. I've been meaning to remove the plugins folder and use some cordova hooks so that the plugins will get installed when you build the app through the ionic command line (i.e: cordova), rather than having to uninstall and install them one by one. I'll open a bug for that.

**Comment by akulkarni9** [comment]
Okay, thank you for help
